services:
  ipfs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ipfs_node
    ports:
      - "${IPFS_SWARM_PORT}:${IPFS_SWARM_PORT}"
      - "${IPFS_API_PORT}:${IPFS_API_PORT}"
      - "${IPFS_GATEWAY_PORT}:${IPFS_GATEWAY_PORT}"
      - "8082:80"  # Uncommon port for Nginx
    env_file:
      - .env
    restart: unless-stopped
